In [39]:
import numpy as np
import pandas as pd

In [3]:
one = np.array(["Apple" , "Mango" , "Banana" , "Orange" , "Kiwi"])

In [4]:
one

array(['Apple', 'Mango', 'Banana', 'Orange', 'Kiwi'], dtype='<U6')

In [5]:
one.ndim

1

In [6]:
two = np.array([[2,5,3,9]])
two

array([[2, 5, 3, 9]])

In [7]:
two.ndim

2

In [8]:
five = np.array([[[[[2,5,1,8,3,0]]]]])
five


array([[[[[2, 5, 1, 8, 3, 0]]]]])

In [9]:
five.ndim

5

In [10]:
five.shape

(1, 1, 1, 1, 6)

In [11]:
two.size

4

In [12]:
print(one.dtype)
print(two.dtype)
five.dtype

<U6
int64


dtype('int64')

In [13]:
five.itemsize

8

In [14]:
one_arr = np.ones((3,5))
one_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
zero_arr = np.zeros((3,5))
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
random_arr = np.random.random((3,5))
random_arr

array([[0.40251811, 0.23033815, 0.6614025 , 0.72163453, 0.14460109],
       [0.26555255, 0.03451611, 0.91132042, 0.02501817, 0.36230973],
       [0.54463348, 0.89258797, 0.83008819, 0.73976198, 0.75207   ]])

In [17]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arrange = np.arange(6)
arrange

array([0, 1, 2, 3, 4, 5])

In [19]:
arrange1 = np.arange(4,15)
arrange1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arrange2 = np.arange(2,50,3)
arrange2

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [21]:
linspace = np.linspace(2,10,40)
linspace

array([ 2.        ,  2.20512821,  2.41025641,  2.61538462,  2.82051282,
        3.02564103,  3.23076923,  3.43589744,  3.64102564,  3.84615385,
        4.05128205,  4.25641026,  4.46153846,  4.66666667,  4.87179487,
        5.07692308,  5.28205128,  5.48717949,  5.69230769,  5.8974359 ,
        6.1025641 ,  6.30769231,  6.51282051,  6.71794872,  6.92307692,
        7.12820513,  7.33333333,  7.53846154,  7.74358974,  7.94871795,
        8.15384615,  8.35897436,  8.56410256,  8.76923077,  8.97435897,
        9.17948718,  9.38461538,  9.58974359,  9.79487179, 10.        ])

In [22]:
my_list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [23]:
my_array = np.array(my_list)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
my_tuple = {1,2,3,4,5,6,7}
my_arr = np.array(my_tuple)
my_arr

array({1, 2, 3, 4, 5, 6, 7}, dtype=object)

In [25]:
my_array[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [26]:
my_array[::-1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
my_array[2::2]

array([ 3,  5,  7,  9, 11, 13, 15])

In [28]:
my_array[1:16:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [29]:
kernel = np.array([[1,2,3],[4,5,6]])
kernel

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
kernel.flatten()

array([1, 2, 3, 4, 5, 6])

In [31]:
array1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
array1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [32]:
array1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [33]:
array2 = np.array([[0,1],[2,3]])
array2

array([[0, 1],
       [2, 3]])

In [34]:
np.resize(array2,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [35]:
import pandas as pd

In [42]:
my_dict = {"Name":["Sahil" , "Shreyash" , "Siddesh" , "Vedant", "Riddesh" , "Soham"],
           "Roll_No": ["39019" , "39014" , "39010" , "3907" , "39020" , "39072"],
          "Age":["21","20","20","22" , "21" , "20"],
          "Attendance":["100","90" ,"80" , "70" , "60" , "50"],}
my_dict

{'Name': ['Sahil', 'Shreyash', 'Siddesh', 'Vedant', 'Riddesh', 'Soham'],
 'Roll_No': ['39019', '39014', '39010', '3907', '39020', '39072'],
 'Age': ['21', '20', '20', '22', '21', '20'],
 'Attendance': ['100', '90', '80', '70', '60', '50']}

In [43]:
df = pd.DataFrame(my_dict)                                                     

In [44]:
df

Name Roll_No Age Attendance
0     Sahil   39019  21        100
1  Shreyash   39014  20         90
2   Siddesh   39010  20         80
3    Vedant    3907  22         70
4   Riddesh   39020  21         60
5     Soham   39072  20         50

In [45]:
data = {
    "Energy Source": ["Solar" , "Wind" , "Hydropower" , "Geothermal" , "Biomass" , "Nuclear"],
    "Energy Consumption":[1200 , np.nan , 2900 , np.nan , 2500 , 3200],
    "Cost Millions ":[200 , 400 , np.nan , 150 , 250 , np.nan]
}

data

{'Energy Source': ['Solar',
  'Wind',
  'Hydropower',
  'Geothermal',
  'Biomass',
  'Nuclear'],
 'Energy Consumption': [1200, nan, 2900, nan, 2500, 3200],
 'Cost Millions ': [200, 400, nan, 150, 250, nan]}

In [46]:
energy_df = pd.DataFrame(data)

energy_df

Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind                 NaN           400.0
2    Hydropower              2900.0             NaN
3    Geothermal                 NaN           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0             NaN

In [47]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Energy Source       6 non-null      object 
 1   Energy Consumption  4 non-null      float64
 2   Cost Millions       4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 276.0+ bytes


In [48]:
energy_df.isna

<bound method DataFrame.isna of   Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind                 NaN           400.0
2    Hydropower              2900.0             NaN
3    Geothermal                 NaN           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0             NaN>

In [49]:
energy_df.isnull

<bound method DataFrame.isnull of   Energy Source  Energy Consumption  Cost Millions 
0         Solar              1200.0           200.0
1          Wind                 NaN           400.0
2    Hydropower              2900.0             NaN
3    Geothermal                 NaN           150.0
4       Biomass              2500.0           250.0
5       Nuclear              3200.0             NaN>

In [50]:
energy_df.describe()

Energy Consumption  Cost Millions 
count            4.000000        4.000000
mean          2450.000000      250.000000
std            881.286938      108.012345
min           1200.000000      150.000000
25%           2175.000000      187.500000
50%           2700.000000      225.000000
75%           2975.000000      287.500000
max           3200.000000      400.000000